# Prepares the fx_* tables for a large Mega firmware and applies (or removes)
# their XOR mask in effect_data.h.
#
# Why: on this Mega the USB-serial upload path corrupts the unmasked effect-data
# byte patterns and avrdude dies partway through the flash write ("timeout" /
# "failed to execute command 0x13"). The very same pages upload fine once the
# bytes are XOR-masked. d_light_effects.ino undoes the mask on every read in
# fx_read(), so the colours on the playfield are unchanged.
#
# effect_data.h is GENERATED by the CnC Light Editor -- run this after every
# regeneration. It also moves the large bank out of .progmem* and behind all
# executable .text.* input. The Arduino AVR core reads its own pin/port tables
# with 16-bit LPM, so letting the bank push those tables above 64 KiB breaks
# digitalRead(), pinMode() and the coil guard. Putting the bank among .text.*
# instead splits the code and triggers broken out-of-range linker relaxations.
# Forgetting the XOR step is not silent: the FX_DATA_MASK_APPLIED define this
# script inserts is checked by an #error in d_light_effects.ino.
#
#   .\mask_effect_data.ps1            # mask + safe flash layout
#                                      # (layout-only if already masked)
#   .\mask_effect_data.ps1 -Unmask    # back to plain data
#
# If a future effect set still fails to upload, change MASK here and
# FX_DATA_MASK in d_light_effects.ino to the same new value and re-run.

param(
  [string]$Path = "$PSScriptRoot\effect_data.h",
  [switch]$Unmask
)

[int]$MASK   = 0x5A
$markerRx    = '^\s*#define\s+FX_DATA_MASK_APPLIED\b'
$farMarkerRx = '^\s*#define\s+FX_DATA_PROGMEM\b'
$farMarker   = '#define FX_DATA_PROGMEM __attribute__((section(".fini1"), used))'
$arrayRx     = '^\s*const\s+uint8_t\s+fx_\w+\[\]\s+(?:PROGMEM|FX_DATA_PROGMEM)\s*=\s*\{'

if (-not (Test-Path $Path)) { Write-Error "not found: $Path"; exit 1 }

$lines    = [System.IO.File]::ReadAllLines($Path)
$markerAt = -1
for ($i = 0; $i -lt $lines.Count; $i++) { if ($lines[$i] -match $markerRx) { $markerAt = $i; break } }
$isMasked = ($markerAt -ge 0)

if ($Unmask -and -not $isMasked) { Write-Error "already unmasked: $Path"; exit 1 }
$transformValues = $Unmask -or -not $isMasked

# On unmask, drop the marker block: the #define plus the comment lines hugging
# it, plus the blank line that separates it from the includes above.
if ($Unmask) {
  $start = $markerAt
  while ($start -gt 0 -and $lines[$start - 1].TrimStart().StartsWith('//')) { $start-- }
  if ($start -gt 0 -and $lines[$start - 1].Trim() -eq '') { $start-- }
  $end = $markerAt
  while ($end -lt $lines.Count - 1 -and $lines[$end + 1].TrimStart().StartsWith('//')) { $end++ }
  $kept = New-Object System.Collections.Generic.List[string]
  for ($i = 0; $i -lt $lines.Count; $i++) { if ($i -lt $start -or $i -gt $end) { $kept.Add($lines[$i]) } }
  $lines = $kept.ToArray()
}

$out     = New-Object System.Collections.Generic.List[string]
$inArr   = $false
$arrays  = 0
$changed = 0
$ev = [System.Text.RegularExpressions.MatchEvaluator]{
  param($m)
  if (-not $script:transformValues) { return $m.Value }
  $script:changed++
  return [string]([int]$m.Value -bxor $script:MASK)
}

foreach ($line in $lines) {
  if (-not $inArr) {
    $preparedLine = [regex]::Replace(
      $line,
      '^(\s*const\s+uint8_t\s+fx_\w+\[\]\s+)PROGMEM(\s*=\s*\{)',
      '$1FX_DATA_PROGMEM$2'
    )
    $out.Add($preparedLine)
    if ($preparedLine -match $arrayRx) { $inArr = $true; $arrays++ }
    continue
  }
  if ($line -match '^\s*\};')             { $inArr = $false; $out.Add($line); continue }
  if ($line.TrimStart().StartsWith('//')) { $out.Add($line); continue }
  $out.Add([regex]::Replace($line, '\d+', $ev))
}

# On a fresh mask, insert the marker block right after the pgmspace include.
if (-not $Unmask -and -not $isMasked) {
  $final = New-Object System.Collections.Generic.List[string]
  $done  = $false
  foreach ($line in $out) {
    $final.Add($line)
    if (-not $done -and $line -match '^\s*#include\s+<avr/pgmspace\.h>') {
      $final.Add("")
      $final.Add("// Must match FX_DATA_MASK in d_light_effects.ino; that file #errors if it doesn't.")
      $final.Add(("#define FX_DATA_MASK_APPLIED 0x{0:X2}" -f $MASK))
      $final.Add("// The fx_* tables below are stored XOR-masked; d_light_effects.ino undoes it in")
      $final.Add("// fx_read(). Without the mask this board's USB-serial upload dies at 28% of the")
      $final.Add("// flash write. If you regenerate this file with the CnC Light Editor, re-run")
      $final.Add("// mask_effect_data.ps1 or the build will stop with an #error.")
      $done = $true
    }
  }
  if (-not $done) { Write-Error "no '#include <avr/pgmspace.h>' line to anchor the marker to"; exit 1 }
  $out = $final
}

# Every generated header also needs the safe flash-section macro. Keep it when
# unmasking: the 64 KiB layout requirement is independent of the XOR encoding.
$hasFarMarker = $false
for ($i = 0; $i -lt $out.Count; $i++) {
  if ($out[$i] -match $farMarkerRx) {
    $out[$i] = $farMarker
    $hasFarMarker = $true
  }
}
if (-not $hasFarMarker) {
  $final = New-Object System.Collections.Generic.List[string]
  $done  = $false
  foreach ($line in $out) {
    $final.Add($line)
    if (-not $done -and $line -match '^\s*#include\s+<avr/pgmspace\.h>') {
      $final.Add("")
      $final.Add("// Keep core tables/code below 64 KiB; .fini1 is appended after all .text.* input.")
      $final.Add($farMarker)
      $done = $true
    }
  }
  if (-not $done) { Write-Error "no '#include <avr/pgmspace.h>' line to anchor FX_DATA_PROGMEM"; exit 1 }
  $out = $final
}

[System.IO.File]::WriteAllLines($Path, $out)
"{0}: {1} arrays, {2} values" -f $(if ($Unmask) { "unmasked" } elseif ($isMasked) { "layout prepared (already masked)" } else { "masked + layout prepared" }), $arrays, $changed
